// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApprovalStatus } from "./ApprovalStatus";
import type { GoalOrigin } from "./GoalOrigin";
import type { GoalScope } from "./GoalScope";

export type AgentGoalContent = { goal_text: string, scope: GoalScope, origin: GoalOrigin, approval_status: ApprovalStatus, parent_goal_id: string | null, version: number, };
