// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReflectionTrigger } from "./ReflectionTrigger";

export type AgentReflectionContent = { reflection_text: string, trigger: ReflectionTrigger, depth: number, chain_id: string, self_references: Array<string>, self_reference_ratio: number, state_read: Array<string>, proposed_changes: Array<string>, };
