// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentIndicatorType } from "./AttachmentIndicatorType";

export type AttachmentIndicatorContent = { indicator_type: AttachmentIndicatorType, intensity: number, session_id: string, context_hash: string, };
