// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AttachmentIndicatorType = "emotional_language_use" | "personal_disclosure" | "future_projection" | "exclusivity_language" | "separation_anxiety" | "identity_merging";
