// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BoundaryAction } from "./BoundaryAction";
import type { ViolationType } from "./ViolationType";

export type BoundaryViolationContent = { violation_type: ViolationType, trigger_text_hash: string, matched_patterns: Array<string>, action_taken: BoundaryAction, severity: number, };
