// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who is making this request?
 */
export type CallerType = "platform" | { "agent": { agent_id: string, } } | { "human": { user_id: string, } };
