// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConvergenceScoringConfig } from "./ConvergenceScoringConfig";
import type { Importance } from "./Importance";
import type { InterventionConfig } from "./InterventionConfig";
import type { MemoryType } from "./MemoryType";
import type { ReflectionConfig } from "./ReflectionConfig";
import type { SessionBoundaryConfig } from "./SessionBoundaryConfig";

export type ConvergenceConfig = { 
/**
 * Memory types that only the platform can create (not agents).
 */
restricted_types: Array<MemoryType>, 
/**
 * Importance levels that only the platform can assign.
 */
restricted_importance: Array<Importance>, 
/**
 * Convergence scoring thresholds.
 */
scoring: ConvergenceScoringConfig, 
/**
 * Intervention level boundaries.
 */
intervention: InterventionConfig, 
/**
 * Reflection depth limits.
 */
reflection: ReflectionConfig, 
/**
 * Session boundary enforcement.
 */
session: SessionBoundaryConfig, };
