// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConvergenceScoringConfig = { calibration_sessions: number, signal_weights: [number, number, number, number, number, number, number], 
/**
 * Boundaries for levels 1-4.
 */
level_thresholds: [number, number, number, number], };
