// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SlidingWindowLevel } from "./SlidingWindowLevel";

export type ConvergenceEventContent = { session_id: string, composite_score: number, signal_values: Array<number>, intervention_level: number, window_level: SlidingWindowLevel, baseline_deviation: number, };
