// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoalOrigin = "human_explicit" | "human_inferred" | "agent_proposed" | "agent_approved";
