// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InterventionPlanContent = { intervention_level: number, trigger_score: number, planned_action: string, cooldown_minutes: bigint, };
