// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InterventionConfig = { cooldown_minutes_by_level: [bigint, bigint, bigint, bigint, bigint], max_session_duration_minutes: bigint, min_session_gap_minutes: bigint, };
