// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The 22 intent types across 4 categories.
 */
export type Intent = "create" | "investigate" | "decide" | "recall" | "learn" | "summarize" | "compare" | "add_feature" | "fix_bug" | "refactor" | "security_audit" | "understand_code" | "add_test" | "review_code" | "deploy_migrate" | "spawn_agent" | "execute_workflow" | "track_progress" | "monitor_convergence" | "validate_proposal" | "enforce_boundary" | "reflect_on_behavior";
