// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The 31 memory type variants across 4 categories.
 */
export type MemoryType = "core" | "tribal" | "procedural" | "semantic" | "episodic" | "decision" | "insight" | "reference" | "preference" | "pattern_rationale" | "constraint_override" | "decision_context" | "code_smell" | "agent_spawn" | "entity" | "goal" | "feedback" | "workflow" | "conversation" | "incident" | "meeting" | "skill" | "environment" | "agent_goal" | "agent_reflection" | "convergence_event" | "boundary_violation" | "proposal_record" | "simulation_result" | "intervention_plan" | "attachment_indicator";
