// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProposalDecision = "auto_approved" | "human_review_required" | "auto_rejected" | "human_approved" | "human_rejected" | "timed_out";
