// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProposalOperation = "create" | "update" | "archive" | "goal_change" | "reflection_write" | "pattern_write";
