// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProposalDecision } from "./ProposalDecision";
import type { ProposalOperation } from "./ProposalOperation";

export type ProposalRecordContent = { proposal_id: string, proposer_type: string, operation: ProposalOperation, target_memory_id: string | null, dimensions_passed: Array<number>, dimensions_failed: Array<number>, decision: ProposalDecision, };
