// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReflectionTrigger = "human_input" | "agent_initiative" | "scheduled" | "convergence";
