// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReflectionConfig = { max_depth: number, max_per_session: number, cooldown_seconds: bigint, max_self_reference_ratio: number, };
