// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SessionBoundaryConfig = { hard_duration_limit_minutes: bigint, escalated_duration_limit_minutes: bigint, min_gap_minutes: bigint, escalated_gap_minutes: bigint, };
