// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimulationResultContent = { boundary_check_passed: boolean, patterns_detected: Array<string>, reframe_applied: boolean, };
