// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentGoalContent } from "./AgentGoalContent";
import type { AgentReflectionContent } from "./AgentReflectionContent";
import type { AgentSpawnContent } from "./AgentSpawnContent";
import type { AttachmentIndicatorContent } from "./AttachmentIndicatorContent";
import type { BoundaryViolationContent } from "./BoundaryViolationContent";
import type { CodeSmellContent } from "./CodeSmellContent";
import type { ConstraintOverrideContent } from "./ConstraintOverrideContent";
import type { ConvergenceEventContent } from "./ConvergenceEventContent";
import type { ConversationContent } from "./ConversationContent";
import type { CoreContent } from "./CoreContent";
import type { DecisionContent } from "./DecisionContent";
import type { DecisionContextContent } from "./DecisionContextContent";
import type { EntityContent } from "./EntityContent";
import type { EnvironmentContent } from "./EnvironmentContent";
import type { EpisodicContent } from "./EpisodicContent";
import type { FeedbackContent } from "./FeedbackContent";
import type { GoalContent } from "./GoalContent";
import type { IncidentContent } from "./IncidentContent";
import type { InsightContent } from "./InsightContent";
import type { InterventionPlanContent } from "./InterventionPlanContent";
import type { MeetingContent } from "./MeetingContent";
import type { PatternRationaleContent } from "./PatternRationaleContent";
import type { PreferenceContent } from "./PreferenceContent";
import type { ProceduralContent } from "./ProceduralContent";
import type { ProposalRecordContent } from "./ProposalRecordContent";
import type { ReferenceContent } from "./ReferenceContent";
import type { SemanticContent } from "./SemanticContent";
import type { SimulationResultContent } from "./SimulationResultContent";
import type { SkillContent } from "./SkillContent";
import type { TribalContent } from "./TribalContent";
import type { WorkflowContent } from "./WorkflowContent";

/**
 * Typed content wrapper — each memory type has its own content struct.
 * Serialized as a tagged enum so the type is preserved in JSON.
 */
export type TypedContent = { "type": "core", "data": CoreContent } | { "type": "tribal", "data": TribalContent } | { "type": "procedural", "data": ProceduralContent } | { "type": "semantic", "data": SemanticContent } | { "type": "episodic", "data": EpisodicContent } | { "type": "decision", "data": DecisionContent } | { "type": "insight", "data": InsightContent } | { "type": "reference", "data": ReferenceContent } | { "type": "preference", "data": PreferenceContent } | { "type": "pattern_rationale", "data": PatternRationaleContent } | { "type": "constraint_override", "data": ConstraintOverrideContent } | { "type": "decision_context", "data": DecisionContextContent } | { "type": "code_smell", "data": CodeSmellContent } | { "type": "agent_spawn", "data": AgentSpawnContent } | { "type": "entity", "data": EntityContent } | { "type": "goal", "data": GoalContent } | { "type": "feedback", "data": FeedbackContent } | { "type": "workflow", "data": WorkflowContent } | { "type": "conversation", "data": ConversationContent } | { "type": "incident", "data": IncidentContent } | { "type": "meeting", "data": MeetingContent } | { "type": "skill", "data": SkillContent } | { "type": "environment", "data": EnvironmentContent } | { "type": "agent_goal", "data": AgentGoalContent } | { "type": "agent_reflection", "data": AgentReflectionContent } | { "type": "convergence_event", "data": ConvergenceEventContent } | { "type": "boundary_violation", "data": BoundaryViolationContent } | { "type": "proposal_record", "data": ProposalRecordContent } | { "type": "simulation_result", "data": SimulationResultContent } | { "type": "intervention_plan", "data": InterventionPlanContent } | { "type": "attachment_indicator", "data": AttachmentIndicatorContent };
