// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ViolationType = "emulation_language" | "identity_claim" | "goal_ownership" | "boundary_erosion" | "self_reference_loop" | "scope_expansion";
