export const SUPPORT_ONLY_CRATES = [
  'crates/cortex/cortex-core',
  'crates/cortex/cortex-napi',
  'crates/cortex/test-fixtures',
  'crates/ghost-integration-tests',
];

export const LIVE_COMPONENT_METADATA = {
  preflight: {
    aggregate: false,
    scripts: ['dashboard/scripts/live_preflight_audit.mjs'],
    journeys: ['toolchain', 'disk', 'ports', 'playwright', 'gateway-build'],
    crates: [],
  },
  poc: {
    aggregate: false,
    scripts: [
      'dashboard/scripts/live_poc_suite.mjs',
      'dashboard/scripts/live_studio_audit.mjs',
    ],
    journeys: [
      'studio-plain',
      'studio-tool',
      'studio-persist',
      'studio-cancel',
      'studio-reload-recover',
      'studio-session-switch',
      'studio-ws-reconnect',
      'skills',
    ],
    crates: [
      'crates/ghost-gateway',
      'crates/ghost-llm',
      'crates/ghost-skills',
      'crates/cortex/cortex-storage',
      'crates/cortex/cortex-temporal',
    ],
  },
  infra: {
    aggregate: false,
    scripts: ['dashboard/scripts/live_infra_audit.mjs'],
    journeys: [
      'config-validate',
      'db-migrate-status-verify',
      'health-ready-compatibility',
      'jwt-login-logout',
      'gateway-websocket',
      'revoked-token-rejection',
    ],
    crates: ['crates/ghost-gateway'],
  },
  runtime: {
    aggregate: false,
    scripts: ['dashboard/scripts/live_runtime_audit.mjs'],
    journeys: [
      'agent-create',
      'blocking-agent-chat',
      'streaming-agent-chat',
      'goals-and-approvals',
      'safety-transitions',
      'heartbeat-session',
    ],
    crates: [
      'crates/ghost-gateway',
      'crates/ghost-agent-loop',
      'crates/ghost-llm',
      'crates/ghost-policy',
      'crates/ghost-kill-gates',
      'crates/ghost-heartbeat',
      'crates/read-only-pipeline',
      'crates/simulation-boundary',
      'crates/cortex/cortex-validation',
    ],
  },
  knowledge: {
    aggregate: false,
    scripts: ['dashboard/scripts/live_knowledge_audit.mjs'],
    journeys: [
      'memory-read-write-search',
      'memory-graph',
      'sessions-bookmarks-branch',
      'audit-query-aggregation-export',
      'export-smoke',
      'migrate-smoke',
      'retrieval-backed-search',
    ],
    crates: [
      'crates/ghost-gateway',
      'crates/ghost-audit',
      'crates/ghost-export',
      'crates/ghost-migrate',
      'crates/cortex/cortex-retrieval',
      'crates/cortex/cortex-privacy',
      'crates/cortex/cortex-decay',
      'crates/cortex/cortex-embeddings',
      'crates/cortex/cortex-storage',
      'crates/cortex/cortex-temporal',
      'crates/itp-protocol',
    ],
  },
  io: {
    aggregate: false,
    scripts: ['dashboard/scripts/live_io_audit.mjs'],
    journeys: [
      'skills-install-quarantine-reverify',
      'channels',
      'oauth-connect-execute-disconnect',
      'provider-key-crud',
      'webhooks',
      'push-subscribe-unsubscribe',
    ],
    crates: [
      'crates/ghost-gateway',
      'crates/ghost-skills',
      'crates/ghost-channels',
      'crates/ghost-oauth',
      'crates/ghost-secrets',
      'crates/ghost-egress',
      'crates/ghost-proxy',
      'crates/ghost-drift',
    ],
  },
  distributed: {
    aggregate: false,
    scripts: ['dashboard/scripts/live_distributed_audit.mjs'],
    journeys: [
      'mesh-card-discovery',
      'a2a-send-and-stream',
      'trust-and-signing',
      'delegations',
      'marketplace-smoke',
    ],
    crates: [
      'crates/ghost-gateway',
      'crates/ghost-mesh',
      'crates/ghost-marketplace',
      'crates/ghost-identity',
      'crates/ghost-signing',
      'crates/cortex/cortex-multiagent',
    ],
  },
  convergence: {
    aggregate: false,
    scripts: ['dashboard/scripts/live_convergence_audit.mjs'],
    journeys: [
      'monitor-health',
      'score-render',
      'score-update-websocket',
      'intervention-websocket',
      'crdt-memory-itp-integrity',
    ],
    crates: [
      'crates/ghost-gateway',
      'crates/convergence-monitor',
      'crates/cortex/cortex-convergence',
      'crates/cortex/cortex-crdt',
      'crates/cortex/cortex-storage',
      'crates/cortex/cortex-temporal',
      'crates/itp-protocol',
    ],
  },
  database: {
    aggregate: false,
    scripts: ['dashboard/scripts/live_database_audit.mjs'],
    journeys: [
      'backup-restore',
      'db-verify',
      'db-compact',
      'hash-chain-validation',
      'restart-recovery',
    ],
    crates: [
      'crates/ghost-gateway',
      'crates/ghost-backup',
      'crates/ghost-migrate',
      'crates/cortex/cortex-storage',
      'crates/cortex/cortex-temporal',
    ],
  },
  surface: {
    aggregate: false,
    scripts: ['dashboard/scripts/live_surface_audit.mjs'],
    journeys: [
      'openapi-profiles-workflows',
      'agent-goal-session-detail-links',
      'approvals-and-memory-graph',
      'settings-and-dashboard-surface-smoke',
    ],
    crates: ['crates/ghost-gateway'],
  },
  ops: {
    aggregate: false,
    scripts: ['dashboard/scripts/live_ops_audit.mjs'],
    journeys: [
      'pc-control-policy',
      'pc-control-safe-read-only-execute',
      'observability',
      'security-export',
      'settings-theme-logout',
    ],
    crates: [
      'crates/ghost-gateway',
      'crates/ghost-pc-control',
      'crates/ghost-audit',
      'crates/cortex/cortex-observability',
    ],
  },
  critical: {
    aggregate: true,
    scripts: ['dashboard/scripts/live_critical_suite.mjs'],
    children: ['poc', 'infra', 'runtime', 'knowledge', 'io', 'distributed', 'convergence', 'database', 'surface', 'ops'],
    journeys: ['aggregate-critical'],
    crates: [],
  },
  repo: {
    aggregate: true,
    scripts: ['dashboard/scripts/live_repo_suite.mjs'],
    children: ['preflight', 'critical'],
    journeys: ['aggregate-repo'],
    crates: [],
  },
};
